### ISSUE TITLE
Feature Request: Please add an option to remove color

### ISSUE THREAD

**Issue by mmcintyre123** [paulpflug/color-tabs#1]
Sometimes I want to clear the color from a tab.  It would be great if this were possible with a shortcut like ctrl+alt+c!  Thanks for considering.

**Comment by paulpflug** [comment]
I have added it in 0.1.0 on `ctrl+alt+x`, there was already another binding on `ctrl+alt+c`
I hope you like it :smile: 

if you have another suggestion regarding keybinding, let me know

**Comment by mmcintyre123** [comment]
Thanks so much!  Works great! :)

**Comment by mmcintyre123** [comment]
:+1:
