### ISSUE TITLE
coloring a unsaved tab is not supported

### ISSUE THREAD

**Issue by bojidar-bg** [paulpflug/color-tabs#11]
With color-tabs-regex this warning message pops up whenever I make a new file (because it has to update all tabs, and it passes through the new tab..). A better solution will be to
1. Color all 'unnamed' tabs in the same color (maybe `:not([data-path])` ?)
2. Silently drop the message when used through the service (e.g. show it only with `ctrl-alt-A`/`ctrl-alt-X`, but not when the service is invoked)

**Comment by bojidar-bg** [comment]
P.S. I just noticed it says "a unsaved tab" instead of "a**n** unsaved tab" :smile:

**Comment by paulpflug** [comment]
I will take the 2. ;)

**Comment by bojidar-bg** [comment]
=) hehe, that's too easy :stuck_out_tongue:

**Comment by paulpflug** [comment]
implemented in 0.1.7
thx for reporting :smiley:

**Comment by bojidar-bg** [comment]
Yeah... that's better :+1:
