### ISSUE TITLE
Broder style not working properly

### ISSUE THREAD

**Issue by mbrammer** [paulpflug/color-tabs#12]
Broder style only works when background style != none.

Atom 1.0.0-1.0.2
color-tabs 0.1.7

**Comment by mbrammer** [comment]
Noticed that the border is only working wen tab is active.

**Comment by paulpflug** [comment]
Which theme are you using? Can you provide a Screenshot of the tab?


Am 9. Juli 2015 09:48:28 schrieb Mischa Brammer <notifications@github.com>:

**Comment by mbrammer** [comment]
I'm using the default theme.
![bildschirmfoto 2015-07-09 um 10 39 23](https://cloud.githubusercontent.com/assets/2786547/8591217/0922d80e-2627-11e5-9ea1-1ede821efd00.png)

Tabs with gradient:
![bildschirmfoto 2015-07-09 um 10 39 59](https://cloud.githubusercontent.com/assets/2786547/8591219/092553ae-2627-11e5-8a74-805ebf42007c.png)

Tabs without gradient (only active tab has visible border):
![bildschirmfoto 2015-07-09 um 10 40 25](https://cloud.githubusercontent.com/assets/2786547/8591218/0923ec12-2627-11e5-9856-1ce102db8c43.png)

**Comment by averrin** [comment]
Yeah, with One Dark tab had "border-bottom", but its invisible 0_o

**Comment by averrin** [comment]
one-dark-ui add css property border-image, which overwrite border-bottom color.

**Comment by mbrammer** [comment]
Thank you :+1:

**Comment by paulpflug** [comment]
published in 0.1.8
Thanks for reporting @mbrammer 
and for fixing @averrin  
:+1:
