### ISSUE TITLE
Gradients and title color

### ISSUE THREAD

**Issue by averrin** [paulpflug/color-tabs#2]
Hello, your plugins is very useful, but have some troubles with my ui=)
So, i make some modifications for more pretty looking:
https://github.com/averrin/color-tabs/commit/553c2ca94b791d5eba20317e97437ec3a561e2bb

This isnt pull request - because it depends from foldername-tabs, but maybe it will be useful for you.

**Comment by paulpflug** [comment]
I love, that you played around with it :smile:
I think I will include an on/off switch for your style.

**Comment by averrin** [comment]
Oh, it would be nice. If you add non-foldername tabs selector, it will works for default atom.

**Comment by averrin** [comment]
Im playing around this style:
![tab-markers](https://cloud.githubusercontent.com/assets/426007/8465481/3c7c7a40-2053-11e5-8229-6e8871fa8543.png)
Colored markers in right-top corner. May be will do pull request. So, style chooser should be select, not checkbox=)

**Comment by averrin** [comment]
but, there are some themes with non-squared tabs...

**Comment by paulpflug** [comment]
theme compatibility is definitely a problem :smile:

hmm colored markers, looks interesting. We can apply the css only on certain themes.. that induces some management

checkout the new version.. I removed the text-coloring from foldername tabs so a special selector isn't needed anymore and I improved the css generation.

**Comment by paulpflug** [comment]
css is getting a bit chaotic in v0.1.4
but all in all a big improvement much thx :+1: 
I hope you like it
