### ISSUE TITLE
Feature request: temporary coloring and color reset

### ISSUE THREAD

**Issue by averrin** [paulpflug/color-tabs#6]
When i use coloring service i need coloring only for existing rules, but your package save it in color-tabs.cson. Maybe you can add some flag for coloring function?
So, i also need reset color for some tab. Imho its a good feature for opened-files package, but now color-tabs isnt supporting this functionality.

Possibly, i will sent pr for this=)

**Comment by paulpflug** [comment]
you remind me, that the reset color functionality is badly documented
you can hit `ctrl+alt+x` to reset color or use the colorTab function like this:
`@changeColor path, undefined`

the saving flag makes sense. I will include it

**Comment by averrin** [comment]
Hmm, i see "save" flag, but didnt understood how it works with service. Seems like you already implement it, but it works like magic=)

**Comment by paulpflug** [comment]
I was wrong, to uncolor you have to call `@changeColor path, false` like [here](https://github.com/paulpflug/color-tabs/blob/master/lib/color-tabs.coffee#L222)
The save flag is implemented but not exposed to the service..
[it is set to always save](https://github.com/paulpflug/color-tabs/blob/master/lib/color-tabs.coffee#L228-229)

**Comment by paulpflug** [comment]
exposed in 0.1.5
:smile:
