### ISSUE TITLE
Document the BackgroundStyle and MarkerStyle options

### ISSUE THREAD

**Issue by bojidar-bg** [paulpflug/color-tabs#7]
Currently one has to search through the code to find such basic options... Maybe also document how to open the config file, because some users might not be accustomed to it :smile: ...

**Comment by averrin** [comment]
You are not need to open config, just open package settings:
![c-t-settings](https://cloud.githubusercontent.com/assets/426007/8528067/47eca84a-2419-11e5-8256-b7488b70c7bc.png)

But maybe some more documentation would be nice.

**Comment by paulpflug** [comment]
added a screenshot to the readme:
![settings](https://cloud.githubusercontent.com/assets/1881921/8529066/df3c337a-2417-11e5-8e73-fecbf0ce2379.png)

thanks for reporting :smiley:
